### ISSUE TITLE
Underglow SMD Leds are on the wrong side of the board

### ISSUE THREAD

**Issue by h4llow3En** [uuupah/pain27#2]
All Underglow Leds are on the backside of the board. Only the two for the Spacebar are on the upside.

**Comment by brneor** [comment]
Well, that's why they're called **under**glow...

**Comment by h4llow3En** [comment]
Then the two on the upsite are wrong. eitherway

**Comment by uuupah** [comment]
as above, the underglow leds are meant to be under the board. backlighting leds are inside the switch, beside the two under the spacebar which are used to get a better light spread under the larger keycap.
