### ISSUE TITLE
There aren't enough keys. WHERE'S THE SHIFT?

### ISSUE THREAD

**Issue by CameronPersonett** [uuupah/pain27#7]

**Comment by xtaran** [comment]
Modifier-on-hold works totally fine for me with Shift, too. "A" is my "Shift" key if I hold it down and it types "a" if just tap it. 🤷🏾‍♂️

**Comment by CameronPersonett** [comment]
How do you type "A"? Double-tap? Triple-tap? 

Can you triple-tap a double-tap? And also, do you really daily drive this thing?

**Comment by xtaran** [comment]
> How do you type "A"? Double-tap? Triple-tap?

Single tap, at least in my config. (I don't use double or triple tap anywhere, but use tap-or-hold and layers a lot.)

In my key mapping, Left Shift is holding A down and pressing another key. (And Right Shift is holding K down in my mapping. So Shift-A is pressing K and keeping it pressed down and then tap A. You of course can also use L instead, if that's more convenient for you. I use L on hold to switch temporarily to another layer.)

Here's my complete [QMK](https://qmk.fm/) key mapping for the Pain27:

![layout](https://github.com/uuupah/pain27_kb/assets/241094/6f8d584c-7ddc-4d62-905d-bcf510e319da)

("Ebene" is German and means "layer". The according [JSON file for this mapping is in this gist](https://gist.github.com/xtaran/94bdebd3e52c3c60128996155c3d8184). You can use this file with e.g. the [web-based QMK Configurator](https://config.qmk.fm/#/wsk/pain27/LAYOUT) to generate a custom firmware for the Pain27.)

> And also, do you really daily drive this thing?

I did for a few days and still occasionally use it on a Raspberry Pi. It's part of my collection of small keyboards.

[Here's a blog posting about using keyboards with very few keys](https://noone.org/blog/English/Computer/Hardware/How%20do%20you%20type%20on%20a%20keyboard%20with%2028%20keys%3F.futile) including a keyboard with just one more key than the Pain27: The [Alpha28](https://github.com/PyrooL/Alpha) — including my key mapping for it and explanations.  That additional key right of L can e.g. be used as Enter on tap and right Shift on hold. My key mapping for the Pain27 (see above) is though very similar and most of the explanations fit there, too. (The other keyboard in this blog posting, a 40% MiniVan keyboard, was my daily driver for much longer, IIRC a year or two, and is now my travel keyboard.)

**Comment by SeibiRiho** [comment]
The "A" key should work as a regular tap. If you use the vanilla layout, does this problem still exist? Maybe you have a fault somewhere (switch, PCB or code (if you have modified it)). Although I have noticed that the hold timeout is a bit short for speedtyping, it just needs some time to get used to (or edit the code).

Side question: is there an album with all of the finished Pain27 builds? Would like to see how mine stacks up to others
